#!/usr/bin/env bash

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

# Ensure PHP-FPM and Nginx run as the correct user
usermod -u $WWWUSER sail
groupmod -g $WWWUSER sail

# Start PHP-FPM
service php8.3-fpm start

# Start Nginx in the foreground
nginx -g 'daemon off;'
